Repository CDS-Mobile1/CDS_iOS, pull requests merged in 2023-05, with the labels that each got.

#2 [Setting] Issue, PR template 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️Setting

#5 [Chore] info.plist 위치 변경으로 인한 빌드 오류 해결
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
Labels: 🏃‍♂️ASAP, ☝️Chore

#14 [Add] Font, Image, Color 추가
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS/Global/Extension/Extension.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UIColor+.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UIFont+.swift
  Instagram-iOS/Instagram-iOS/Global/Literal/ImageLiteral.swift
  Instagram-iOS/Instagram-iOS/Global/Literal/Literal.swift
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/camera.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/camera.imageset/camera.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/dmBlack.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/dmBlack.imageset/dm.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/dmWhite.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/dmWhite.imageset/Frame.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/home.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/home.imageset/home.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/homeFilled.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/homeFilled.imageset/homeFilled.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/likeBlack.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/likeBlack.imageset/like.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/likeBlackFilled.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/likeBlackFilled.imageset/likeBlackFilled.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/likeWhite.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/likeWhite.imageset/Frame-1.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/likeWhiteFilled.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/likeWhiteFilled.imageset/Property 1 white=on.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/newPost.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/newPost.imageset/newStory.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/newPostFilled.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/newPostFilled.imageset/newStoryFilled.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/newdm.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/newdm.imageset/newdm.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/profile.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/profile.imageset/Property 1=alart_off.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/reels.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/reels.imageset/video.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/reelsFilled.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/reelsFilled.imageset/videoFilled.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/search.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/search.imageset/search.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/searchFilled.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/searchFilled.imageset/searchFilled.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/tagged.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/tagged.imageset/tagged.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Image/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Image/defaultProfile.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Image/defaultProfile.imageset/defaultImage.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Image/instagramLogo.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Image/instagramLogo.imageset/instagramLogo.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Font/AppleSDGothicNeoB.ttf
  Instagram-iOS/Instagram-iOS/Global/Resource/Font/AppleSDGothicNeoM.ttf
  Instagram-iOS/Instagram-iOS/Global/Resource/Font/AppleSDGothicNeoSB.ttf
  Instagram-iOS/Instagram-iOS/Global/Resource/Font/SF-Pro-Text-Medium.otf
  Instagram-iOS/Instagram-iOS/Global/Resource/Font/SF-Pro-Text-Regular.otf
  Instagram-iOS/Instagram-iOS/Global/Resource/Font/SF-Pro-Text-Semibold.otf
  Instagram-iOS/Instagram-iOS/Global/Supports/Info.plist
Labels: 📕Add

#17 [Feat] extension 및 SizeLiteral 추가
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS/Global/Extension/UIView+.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UIViewController+.swift
  Instagram-iOS/Instagram-iOS/Global/Literal/SizeLiteral.swift
Labels: 🦾Feat

#20 [Feat] NewPost View 완성
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS/Global/Base/BaseViewController.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UIFont+.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UIViewController+.swift
  Instagram-iOS/Instagram-iOS/Global/Literal/ImageLiteral.swift
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/Back.imageset/Back.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/Back.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/addCell.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/addCell.imageset/addCell.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/addPlace.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/addPlace.imageset/material-symbols_location-on-outline-rounded.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/advancedSetting.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/advancedSetting.imageset/uil_setting.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/facebook.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/facebook.imageset/material-symbols_share.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/rightChevron.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/rightChevron.imageset/rightChevron.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/tagSomeone.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/tagSomeone.imageset/account.pdf
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Image/defaultImage.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Image/defaultImage.imageset/defaultImage.pdf
  Instagram-iOS/Instagram-iOS/Global/Supports/Info.plist
  Instagram-iOS/Instagram-iOS/Global/Supports/SceneDelegate.swift
  Instagram-iOS/Instagram-iOS/Global/UIComponent/BackButton.swift
  Instagram-iOS/Instagram-iOS/Screens/NewPost/BottomMenuContentView.swift
  Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPost.swift
  Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/CollectionViewAddCellButton.swift
  Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostImageCollectionViewCell.swift
  Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
Labels: 🦾Feat

#21 [Feat] 사랑장 및 BOJ 가 사용할 User Profile Cell 완료
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS/Global/Extension/UIView+.swift
  Instagram-iOS/Instagram-iOS/Global/UIComponent/UserProfileView.swift
  Instagram-iOS/Instagram-iOS/Screens/ViewController.swift
Labels: 🦾Feat

#26 [Feat] #19 - DMList Navibar UI 구현
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS/Global/Base/BaseViewController.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UIFont+.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UIStackView+.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UITextfield+.swift
  Instagram-iOS/Instagram-iOS/Global/Literal/ImageLiteral.swift
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/ArrowBack.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/ArrowBack.imageset/Vector 968.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/ArrowBack.imageset/Vector 968@2x.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/ArrowBack.imageset/Vector 968@3x.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/ArrowBottom.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/ArrowBottom.imageset/Vector 969.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/ArrowBottom.imageset/Vector 969@2x.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/ArrowBottom.imageset/Vector 969@3x.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/searchDm.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/searchDm.imageset/Group 36937.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/searchDm.imageset/Group 36937@2x.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/searchDm.imageset/Group 36937@3x.png
  Instagram-iOS/Instagram-iOS/Global/Resource/Font/SF-Pro-Text-Bold.ttf
  Instagram-iOS/Instagram-iOS/Global/Supports/Info.plist
  Instagram-iOS/Instagram-iOS/Screens/DMList/DMList.swift
Labels: 🦾Feat

#23 NavigationBar UI 구현
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS.xcodeproj/project.xcworkspace/xcuserdata/kimsarang.xcuserdatad/UserInterfaceState.xcuserstate
  Instagram-iOS/Instagram-iOS.xcodeproj/xcuserdata/kimsarang.xcuserdatad/xcschemes/xcschememanagement.plist
  Instagram-iOS/Instagram-iOS/Global/Supports/SceneDelegate.swift
  Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
Labels: 🦾Feat

#32 [Feat] #24 - story UI 레이아웃 구현
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS.xcodeproj/project.xcworkspace/xcuserdata/kimsarang.xcuserdatad/UserInterfaceState.xcuserstate
  Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeed.swift
  Instagram-iOS/Instagram-iOS/Screens/MainFeed/MainFeedViewController.swift
  Instagram-iOS/Instagram-iOS/Screens/MainFeed/StoryCollection/StoryCollectionView.swift
  Instagram-iOS/Instagram-iOS/Screens/MainFeed/StoryCollection/StoryCollectionViewCell.swift
Labels: 🏃‍♂️ASAP, 🦾Feat

#31 [Setting] API 연결을 위한 초기 세팅
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS/Global/Supports/Info.plist
  Instagram-iOS/Instagram-iOS/Network/API/API.swift
  Instagram-iOS/Instagram-iOS/Network/API/Config.swift
  Instagram-iOS/Instagram-iOS/Network/API/NetworkResult.swift
  Instagram-iOS/Instagram-iOS/Network/Service/BaseAPIService.swift
Labels: ⚙️Setting, 🏃‍♂️ASAP

#28 [Feat] Story UI 완성
  Instagram-iOS/Instagram-iOS.xcodeproj/project.pbxproj
  Instagram-iOS/Instagram-iOS/Global/Extension/UITextField+.swift
  Instagram-iOS/Instagram-iOS/Global/Extension/UITextfield+.swift
  Instagram-iOS/Instagram-iOS/Global/Literal/ImageLiteral.swift
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/sampleProfileImage.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/setting.imageset/Contents.json
  Instagram-iOS/Instagram-iOS/Global/Resource/Assets.xcassets/Icon/setting.imageset/setting.pdf
  Instagram-iOS/Instagram-iOS/Global/UIComponent/CommonButton.swift
  Instagram-iOS/Instagram-iOS/Global/UIComponent/UserProfileView.swift
  Instagram-iOS/Instagram-iOS/Network/Models/Story.swift
  Instagram-iOS/Instagram-iOS/Network/Models/UserWithStory.swift
  Instagram-iOS/Instagram-iOS/Screens/NewPost/NewPostImageCollection/NewPostViewController.swift
  Instagram-iOS/Instagram-iOS/Screens/Story/Story.swift
  Instagram-iOS/Instagram-iOS/Screens/Story/StoryContentViewController.swift
  Instagram-iOS/Instagram-iOS/Screens/Story/StoryPageViewController.swift
  Instagram-iOS/Instagram-iOS/Screens/ViewController.swift
Labels: 🦾Feat
